FROM mcr.microsoft.com/dotnet/runtime:10.0 AS base


USER root
RUN apt-get update && \
    apt-get install -y libkrb5-3 && \
    rm -rf /var/lib/apt/lists/*

USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Snowflake/Snowflake.csproj", "Snowflake/"]
RUN dotnet restore "Snowflake/Snowflake.csproj"
COPY . .
WORKDIR "/src/Snowflake"
RUN dotnet build "./Snowflake.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Snowflake.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Snowflake.dll"]
